### ISSUE TITLE
URL Routes need to be decided on

### ISSUE THREAD

**Issue by jacobm001** [jacobm001/independence_water#2]
We need to determine what the actual routes will be for the API. This will primarily need to be a decision made by Tyler and Alex. I have created a [wiki page](https://github.com/jacobm001/independence_water/wiki/Routes), that has some example routes.

**Comment by merrilal** [comment]
Day
Per day tab
Per day: last read on day minus last read on previous day, current day read ( currentdayread - prevdayread )
Monthly Daily Average: current day read minus last read of previous month divided by day in month ( (currentdayread - prevdayread) \ dayofmonth )
Yearly Daily Average: current day read minus last read of previous year divided by day of year ( (currentdayread - prevyearlastread) \ dayofyear )

Year to date day
Current day read minus last read of previous month ( currentdayread - lastreadprevmonth )

Weekly reads
Per week
Per week: last read of week - last read of previous week
Average weekly use: (last read of current week - last week read of previous year) \ number of current week in current year

Week to date: last read of current week - last week read of previous year

Monthly reads
Per month
Per month: last read of month - last read of previous month
Average monthly use: (last read of current month - last month read of previous year) \ number of current month in current year

month to date: last read of current month - last month read of previous year
